server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001       #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service    #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         #断言，路径相匹配的进路由
        - id: payment_routh2 #payment_route#
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**          #断言，路径相匹配的进行路由
#            - After=2020-07-15T20:23:36.741360800+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy
#            - Header=X-Request-Id,\d+   #请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=*.atguigu.com
#            - Method=get
#            - Query=username,\d+
      discovery:
        locator:
          enabled: true # 开启注册中心动态创建路由的功能，利用微服务名进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
